////////////////////////////////////////////////////////////////////////////////
// NOTE : Generated by slothjson. It is NOT supposed to modify this file.
////////////////////////////////////////////////////////////////////////////////
#ifndef __loginparam_20180602124140_h__
#define __loginparam_20180602124140_h__

#include "slothjson.h"

using namespace slothjson;

struct LoginParam
{
    std::string code;

    void skip_code() { __skip_code = true; }

    bool json_has_code() const { return __json_has_code; }

    LoginParam();
    LoginParam& operator=(const LoginParam& obj_val);
    bool operator==(const LoginParam& obj_val) const;
    bool encode(allocator_t& alloc, rapidjson::Value& json_val) const;
    bool decode(const rapidjson::Value& json_val);

private:
    bool __skip_code;

    bool __json_has_code;
};

bool encode(const LoginParam& obj_val, allocator_t& alloc, rapidjson::Value& json_val);
bool decode(const rapidjson::Value& json_val, LoginParam& obj_val);


#endif // __loginparam_20180602124140_h__