////////////////////////////////////////////////////////////////////////////////
// NOTE : Generated by slothjson. It is NOT supposed to modify this file.
////////////////////////////////////////////////////////////////////////////////
#include "LoginParam.h"


LoginParam::LoginParam()
{
    __skip_code = false;
    __json_has_code = false;
}

LoginParam& LoginParam::operator=(const LoginParam& obj_val)
{
    this->code = obj_val.code;
    return *this;
}

bool LoginParam::operator==(const LoginParam& obj_val) const
{
    if (!(this->code == obj_val.code)) return false;
    return true;
}

bool LoginParam::encode(allocator_t& alloc, rapidjson::Value& json_val) const
{
    do
    {
        json_val.SetObject();
        if (!__skip_code && !encode_field(code, "code", alloc, json_val)) break;

        return true;
    } while (0);

    return false;
}

bool LoginParam::decode(const rapidjson::Value& json_val)
{
    do
    {
        if (!decode_field(json_val, "code", code, __json_has_code)) break;

        return true;
    } while (0);

    return false;
}

bool encode(const LoginParam& obj_val, allocator_t& alloc, rapidjson::Value& json_val)
{
    return obj_val.encode(alloc, json_val);
}

bool decode(const rapidjson::Value& json_val, LoginParam& obj_val)
{
    return obj_val.decode(json_val);
}
