////////////////////////////////////////////////////////////////////////////////
// NOTE : Generated by slothjson. It is NOT supposed to modify this file.
////////////////////////////////////////////////////////////////////////////////
#ifndef __loginbackparam_20180605171741_h__
#define __loginbackparam_20180605171741_h__

#include "slothjson.h"

using namespace slothjson;

struct LoginBackParam
{
    int32_t expire;
    std::string session_id;
    std::string openid;

    void skip_expire() { __skip_expire = true; }
    void skip_session_id() { __skip_session_id = true; }
    void skip_openid() { __skip_openid = true; }

    bool json_has_expire() const { return __json_has_expire; }
    bool json_has_session_id() const { return __json_has_session_id; }
    bool json_has_openid() const { return __json_has_openid; }

    LoginBackParam();
    LoginBackParam& operator=(const LoginBackParam& obj_val);
    bool operator==(const LoginBackParam& obj_val) const;
    bool encode(allocator_t& alloc, rapidjson::Value& json_val) const;
    bool decode(const rapidjson::Value& json_val);

private:
    bool __skip_expire;
    bool __skip_session_id;
    bool __skip_openid;

    bool __json_has_expire;
    bool __json_has_session_id;
    bool __json_has_openid;
};

bool encode(const LoginBackParam& obj_val, allocator_t& alloc, rapidjson::Value& json_val);
bool decode(const rapidjson::Value& json_val, LoginBackParam& obj_val);


#endif // __loginbackparam_20180605171741_h__