////////////////////////////////////////////////////////////////////////////////
// NOTE : Generated by slothjson. It is NOT supposed to modify this file.
////////////////////////////////////////////////////////////////////////////////
#ifndef __loginbackparam_20180601165154_h__
#define __loginbackparam_20180601165154_h__

#include "slothjson.h"
#include "UserInfo.h"

using namespace slothjson;

struct LoginBackParam
{
    int32_t code;
    std::string desc;
    std::vector<UserInfo > data;

    void skip_code() { __skip_code = true; }
    void skip_desc() { __skip_desc = true; }
    void skip_data() { __skip_data = true; }

    bool json_has_code() const { return __json_has_code; }
    bool json_has_desc() const { return __json_has_desc; }
    bool json_has_data() const { return __json_has_data; }

    LoginBackParam();
    LoginBackParam& operator=(const LoginBackParam& obj_val);
    bool operator==(const LoginBackParam& obj_val) const;
    bool encode(allocator_t& alloc, rapidjson::Value& json_val) const;
    bool decode(const rapidjson::Value& json_val);

private:
    bool __skip_code;
    bool __skip_desc;
    bool __skip_data;

    bool __json_has_code;
    bool __json_has_desc;
    bool __json_has_data;
};

bool encode(const LoginBackParam& obj_val, allocator_t& alloc, rapidjson::Value& json_val);
bool decode(const rapidjson::Value& json_val, LoginBackParam& obj_val);


#endif // __loginbackparam_20180601165154_h__